server:
  port: 10086
#  官方默认8761
spring:
  application:
    #服务名称
    name: eureka-server
eureka:
  client:
    service-url:
#eureka集群，10086把自己注册到10087
      defaultZone: http://127.0.0.1:10086/eureka
    register-with-eureka: false
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 30000



#   eureka集群不能配置这个instance，配置了就不能两个eureka互相注册，同步信息
#  instance:
#    prefer-ip-address: true
#    ip-address: 127.0.0.1

